name = "fake-identity-generator"
compatibility_date = "2025-07-13"

[build]
command = "npm run build" # Jika ada proses build, atau hapus jika statis

pages_build_output_dir = "./dist" # Ganti 'dist' sesuai folder output file statis Anda
